### PR TITLE
Feat generate results on expiry

### PR DESCRIPTION
**Pull request by TeeWhyKay**
## Why

This pull request is needed because:

* Automation of result generation when the the session expires.
* Automation of cancelling scheduled job when inviter clicks on 'Generate Results' button before expiry.

[Link to Card](https://trello.com/c/2CZHkFpb)

## What

This pull request introduces the following:
 * Added scheduled job to generate results at session expiry.
 * Scheduled job also sends email to participants once results are generated.
 * Added sidekiq_jid (sidekiq job id) to each chompsession
 * This is to help quickly identify where the scheduled job is in redis and delete the job when the inviter manually closes the session and generates results before session expires.
 * Extra worker to actually remove the scheduled job, so that it does not block. This is a way to sidestep the sidekiq gem limitation has deletion of scheduled job has a linear run time. Underneath, it does a linear search by job id then deletes it.

## How to Test

1. Create a ChompSession in browser
2. Submit 1 user preference for that ChompSession
3. In terminal, `rails c` and type `jid = ChompSession.last.sidekiq_jid` to get the scheduled job id in sidekiq redis.
4. To get the job from sidekiq, run `Sidekiq::ScheduledSet.new.find_job(jid)`
5. Now go back to browser and click on 'Generate Results'
6. If you try to run `Sidekiq::ScheduledSet.new.find_job(jid)` again it should return nil as the scheduled job has been deleted from sidekiq redis. 🎉

### CODE REVIEW

**Comment by TeeWhyKay** [comment]
[Generate ChompSession after timelimit, using sidekiq](https://trello.com/c/2CZHkFpb/136-generate-chompsession-after-timelimit-using-sidekiq)

**Comment by TeeWhyKay** [comment]
[Generate ChompSession after timelimit, using sidekiq](https://trello.com/c/2CZHkFpb/136-generate-chompsession-after-timelimit-using-sidekiq)

**Review by mxng — APPROVED** [review]
Looks fine

**Review by tjw0612 — APPROVED** [review]
looks good

**Review by amelialimyh — APPROVED** [review]
Looks okay

**Review by mxng — APPROVED** [review]
👌 👍

**Review by tjw0612 — APPROVED** [review]
nice, great work for making the quick change

**Pull request merged**
