### PR TITLE
Map function

### PR DESCRIPTION
**Pull request by tjw0612**
## Why

Good-to-have function of interactive map

image

[Link to Card]()

## What

This pull request introduces the following:

 * `Changes introduced`

`Add Implementation details if needed`

### Screenshot

`Attach any screenshots here. Remove when unneeded`

## How to Test

`Give the reviewer(s) some clues on how to test your PR`

## Other

`This section is for things that can't be put into the previous sections. Remove when unneeded`

### CODE REVIEW

**Review by mxng — APPROVED** [review]
Really cool. Works well on mobile and desktop!

**Review by amelialimyh — APPROVED** [review]
Very cool!

**Comment by mxng** [comment]
[Interactive map to reflect location](https://trello.com/c/bQ5hnaTf/52-interactive-map-to-reflect-location)

**Comment by mxng** [comment]
Btw if you see this before you merge, would you mind giving it a "rounded" class so the map has borders?

**Review by TeeWhyKay — APPROVED** [review]
very cool and useful map!

**Pull request merged**
