### PR TITLE
Set color scheme

### PR DESCRIPTION
**Pull request by mxng**
Color scheme & basic font setup

We can use 

`$chomp-font` for the stylized thicker lines
`$chomp-font-light` for the stylized thinner lines
`$chomp-font-black` for the thick lines with no gaps inside

Screenshot 2021-09-25 at 8 42 15 AM
Screenshot 2021-09-25 at 8 42 55 AM

### CODE REVIEW

**Comment by mxng** [comment]
primary & success & info has also been changed, pls look at the files changed

**Comment by tjw0612** [comment]
image
I tried to see on heroku, looks good. helping to attach images here for your reference.

image

**Review by tjw0612 — APPROVED** [review]
looks good

**Comment by mxng** [comment]
The button on another branch is updated so it looks like
Screenshot 2021-09-25 at 12 59 48 PM
 Now, but not on this branch, is on a branch on top of this branch (branchception)

**Pull request merged**
