### PR TITLE
Star Rating System Implemented

### PR DESCRIPTION
**Pull request by tjw0612**
## Why

This pull request is needed because:

Implemented a star-based rating system. If you guys are interested, can take a look and merge.

image

image

image

image

image

### CODE REVIEW

**Review by mxng — APPROVED** [review]
Wow thanks! Was about to try doing this then saw your PR

**Comment by mxng** [comment]
@tjw0612 Can you resolve the conflicts? Then can merge! Remove the titles from reviews

**Review by mxng — CHANGES_REQUESTED** [review]
Ps I forgot to mention I think you need to add the same form from _form.html.erb to _edit_review_form.html.erb! else during edit is back to old format
Screenshot 2021-10-05 at 5 41 15 PM

**Comment by tjw0612** [comment]
> @tjw0612 Can you resolve the conflicts? Then can merge! Remove the titles from reviews

Paiseh just resolved the conflicts le

**Comment by tjw0612** [comment]
> Ps I forgot to mention I think you need to add the same form from _form.html.erb to _edit_review_form.html.erb! else during edit is back to old format Screenshot 2021-10-05 at 5 41 15 PM

Hmmm I purposely left the edit_review_form portion out, cause I thought it looks kinda weird to have stars again in a smaller section below the restaurant. Haha if you wanna add, I let you pr

**Comment by tjw0612** [comment]
> Ps I forgot to mention I think you need to add the same form from _form.html.erb to _edit_review_form.html.erb! else during edit is back to old format Screenshot 2021-10-05 at 5 41 15 PM

Yup made the changes to the edit form as well. Thanks for the reminder. Previously look weird when one user can have many reviews. Now is 1 to 1, the star system looks good.

image

**Review by mxng — APPROVED** [review]
looks ok

**Pull request merged**
