### PR TITLE
Add bg to landing

### PR DESCRIPTION
**Pull request by mxng**
## Why

Our site has no pics 😢 

## What

This pull request introduces the following:

 * We have a picture for landing page

### Screenshot

PC:
Screenshot 2021-09-26 at 9 30 42 PM

iPad:
Screenshot 2021-09-26 at 9 30 15 PM

iPhone:
Screenshot 2021-09-26 at 9 30 31 PM

Animation:

https://user-images.githubusercontent.com/11084577/134810849-8fab9ad6-d62f-4088-8a3b-27f432427d67.mov

### CODE REVIEW

**Comment by mxng** [comment]
Btw do you guys think the button will sound less as if the friends need to sign up as well if we change the button text to:

`Create a group & share with your friends` or `Create a group and get started` or `Create a group to begin`?

**Comment by mxng** [comment]
Need to work on navbar on another branch in case the bg gets screwed up.

**Comment by mxng** [comment]
[Add more details (maybe under the banner) about what the CHOMP website is about in the LANDING PAGE](https://trello.com/c/1s09xwI2/117-add-more-details-maybe-under-the-banner-about-what-the-chomp-website-is-about-in-the-landing-page)

**Comment by mxng** [comment]
[Add tagline: Can't decide on where to eat? Let Chomp decide for you](https://trello.com/c/yDql08Tf/125-add-tagline-cant-decide-on-where-to-eat-let-chomp-decide-for-you)

**Comment by mxng** [comment]
Realise I need to make the div of the banner have background colour black or something to remove the white edges at the sides cos it's actually blending the image with the white default background colour.

If you read this please don't merge. If you merge I know you didn't read! Then I'll just do a hotfix.

**Comment by mxng** [comment]
There should be no more white edges on the HOME PAGE ONLY

**Comment by TeeWhyKay** [comment]
> Btw do you guys think the button will sound less as if the friends need to sign up as well if we change the button text to:
> 
> `Create a group & share with your friends` or `Create a group and get started` or `Create a group to begin`?

`Create a group & share with your friends` this is fine tbh as the call to action.

**Review by TeeWhyKay — APPROVED** [review]
Looks fine! good job.

Do note that the fonts still don't work on heroku

**Review by amelialimyh — APPROVED** [review]
Looks good!

**Review by tjw0612 — APPROVED** [review]
looks good, saw how it looks like

**Pull request merged**
