### PR TITLE
Feature edit reviews

### PR DESCRIPTION
**Pull request by mxng**
## Why

Reviews can't be edited

## What

Now you can edit reviews

### CODE REVIEW

**Comment by mxng** [comment]
[Edit reviews](https://trello.com/c/UvRLHZkV/99-edit-reviews)

**Review by TeeWhyKay — APPROVED** [review]
nice job using stimulus for editing reviews and displaying them so far. Do try to test on heroku by spinning up an app with your PR  👍

**Comment by mxng** [comment]
https://user-images.githubusercontent.com/11084577/134770250-8ad03048-01d4-4a3e-8a67-b372f04c872e.mov

**Comment by mxng** [comment]
Btw, this does not account for if someone else logs in to change other person's reviews. I haven't tested it for that. Good enough for demo day though.

**Review by amelialimyh — APPROVED** [review]
Looks great

**Comment by mxng** [comment]
@TeeWhyKay I can't sign up to test

image

test@test.com and admin account can't be used to login too.

**Comment by mxng** [comment]
@tjw0612 if you think is okay feel free to merge

**Pull request merged**
