### PR TITLE
Add meetup details to responses show

### PR DESCRIPTION
**Pull request by mxng**
## Why

- Not enough details on the pages: AFTER RESPONSES and AFTER CHOMP SESSION CREATION.
- The cuisine selection feedback is not obvious enough

## What

- Adds more details to each pages
- Cuisine selection feedback is changed. Refer to video:

### Screenshot

https://user-images.githubusercontent.com/11084577/134796565-3f1b7e9a-1633-4731-9748-22f940c76417.mov

### How to test

Go to the PR and `rails s` and go through the flow.

### CODE REVIEW

**Comment by mxng** [comment]
https://user-images.githubusercontent.com/11084577/134694175-da0684a4-9288-4733-a121-8ede7d12a61d.mov

I made the selection look like this, is it ok?

**Comment by mxng** [comment]
Screenshot 2021-09-24 at 10 46 01 PM

It looks like this in desktop mode.

In a way I feel it's not obvious enough, but I can't select the text in css.

**Comment by mxng** [comment]
Screenshot 2021-09-24 at 10 52 09 PM

The budget looks like that now btw... Can't do a slider and radio is ugly as heck.

The design for the **budget field** needs work since it looks different from the **location field** which I did not do on. **Anyone interested?**
Screenshot 2021-09-24 at 10 53 26 PM

**Comment by TeeWhyKay** [comment]
> 
> ## Why
> 
> Not enough details on the pages: AFTER RESPONSES and AFTER CHOMP SESSION CREATION.
> ## What
> 
> Adds more details
> ### Screenshot
> 
> Screenshot 2021-09-24 at 9 21 26 PM
> Screenshot 2021-09-24 at 9 21 56 PM

In the UI, the header states Opinion submitted but on the button it's edit preference. Why not name it the same thing?
I think its more intuitive if the header is renamed 'Preference Submitted' , then the button is Edit Preference. Then we don't need the extra text "made a mistake, have no fear.. etc" as it looks very wordy.

**Comment by TeeWhyKay** [comment]
> 
> Screen.Recording.2021-09-24.at.10.37.09.PM-1.mov
> 
> I made the selection look like this, is it ok?

I'm not sure what's the initial state of the cuisine cards when the page is loaded.
So the cuisine cards are all true color at first, and selecting them will grey it out? 
If that's the case it feels like I'm not selecting it if its greyed out...It feels like I'm indicating what cuisines I don't want.

Some inspiration for you? 
[Material design selection](https://material.io/design/interaction/selection.html#item-selection)

**Comment by TeeWhyKay** [comment]
> 
> 
> Screenshot 2021-09-24 at 10 52 09 PM
> 
> The budget looks like that now btw... Can't do a slider and radio is ugly as heck.
> 
> The design for the **budget field** needs work since it looks different from the **location field** which I did not do on. **Anyone interested?**
> Screenshot 2021-09-24 at 10 53 26 PM

I agree that radio buttons are gross.
Try slider? and only have 4 steps [$,$$,$$$,$$$$]
[HTML slider](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range)

**Comment by amelialimyh** [comment]
> > Screen.Recording.2021-09-24.at.10.37.09.PM-1.mov
> > I made the selection look like this, is it ok?
> 
> I'm not sure what's the initial state of the cuisine cards when the page is loaded.
> So the cuisine cards are all true color at first, and selecting them will grey it out?
> If that's the case it feels like I'm not selecting it if its greyed out...It feels like I'm indicating what cuisines I don't want.
> 
> Some inspiration for you?
> [Material design selection](https://material.io/design/interaction/selection.html#item-selection)

The forms used to be true color and if the user clicks on it, a green border will appear to show that it’s been selected

**Comment by amelialimyh** [comment]
> > Screenshot 2021-09-24 at 10 52 09 PM
> > The budget looks like that now btw... Can't do a slider and radio is ugly as heck.
> > The design for the **budget field** needs work since it looks different from the **location field** which I did not do on. **Anyone interested?**
> > Screenshot 2021-09-24 at 10 53 26 PM
> 
> I agree that radio buttons are gross.
> Try slider? and only have 4 steps [$,$$,$$$,$$$$]
> [HTML slider](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range)

Yeah I like the idea of a slider though we probably should have an indicator of what $ means because $ could mean $15 or below to you but it could refer to $5 instead to me.

**Comment by mxng** [comment]
> > Screen.Recording.2021-09-24.at.10.37.09.PM-1.mov
> > I made the selection look like this, is it ok?
> 
> I'm not sure what's the initial state of the cuisine cards when the page is loaded.
> So the cuisine cards are all true color at first, and selecting them will grey it out?
> If that's the case it feels like I'm not selecting it if its greyed out...It feels like I'm indicating what cuisines I don't want.
> 
> Some inspiration for you?
> [Material design selection](https://material.io/design/interaction/selection.html#item-selection)

They are greyed out first then if you select them they are colored.

I can try to add a checkbox overlay and invert the way it is now so that it looks like the Google Keep example:

Screenshot 2021-09-25 at 10 27 24 AM

**Comment by mxng** [comment]
> > > Screenshot 2021-09-24 at 10 52 09 PM
> > > The budget looks like that now btw... Can't do a slider and radio is ugly as heck.
> > > The design for the **budget field** needs work since it looks different from the **location field** which I did not do on. **Anyone interested?**
> > > Screenshot 2021-09-24 at 10 53 26 PM
> > 
> > 
> > I agree that radio buttons are gross.
> > Try slider? and only have 4 steps [$,$$,$$$,$$$$]
> > [HTML slider](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range)
> 
> Yeah I like the idea of a slider though we probably should have an indicator of what $ means because $ could mean $15 or below to you but it could refer to $5 instead to me.

Will be nice if instead of $ $$ $$$ $$$$ we show the value cos I personally dislike google maps because the $ is too vague

**Comment by mxng** [comment]
@crazytrollgirl There's a way for you to create a branch out of my this branch, so you can work with the changes already there. Then there's a way to push also

`git push --set-upstream origin branch-out-of-a-previous-branch-name`
Screenshot 2021-09-25 at 10 30 55 AM

**Comment by mxng** [comment]
Screenshot 2021-09-25 at 11 01 46 AM


What it looks like now with title and updated meetup details format ^, the moment a friend or admin enters the input opinion page for the first time.

**Comment by amelialimyh** [comment]
> @crazytrollgirl There's a way for you to create a branch out of my this branch, so you can work with the changes already there. Then there's a way to push also
> 
> `git push --set-upstream origin branch-out-of-a-previous-branch-name`
> Screenshot 2021-09-25 at 10 30 55 AM

Okay then I shall get cracking

**Comment by mxng** [comment]
I'll be resolving conflicts now

**Comment by mxng** [comment]
[Cuisine selection not obvious enough](https://trello.com/c/KmkWpAWe/113-cuisine-selection-not-obvious-enough)

**Comment by mxng** [comment]
[Context of the meetup on the RESPONSE page](https://trello.com/c/ic678yiG/119-context-of-the-meetup-on-the-response-page)

**Comment by mxng** [comment]
[After joining the session as a friend, see the Session name, date & time](https://trello.com/c/0GoVWG1D/123-after-joining-the-session-as-a-friend-see-the-session-name-date-time)

**Comment by TeeWhyKay** [comment]
> > > Screen.Recording.2021-09-24.at.10.37.09.PM-1.mov
> > > I made the selection look like this, is it ok?
> > 
> > 
> > I'm not sure what's the initial state of the cuisine cards when the page is loaded.
> > So the cuisine cards are all true color at first, and selecting them will grey it out?
> > If that's the case it feels like I'm not selecting it if its greyed out...It feels like I'm indicating what cuisines I don't want.
> > Some inspiration for you?
> > [Material design selection](https://material.io/design/interaction/selection.html#item-selection)
> 
> They are greyed out first then if you select them they are colored.
> 
> I can try to add a checkbox overlay and invert the way it is now so that it looks like the Google Keep example:
> 
> Screenshot 2021-09-25 at 10 27 24 AM

@mxng @crazytrollgirl i think it makes more sense when the user can see the true color of the cuisine, and then selecting it causes it to have an indicator that its selected?

**Comment by mxng** [comment]
I shall revert it tomorrow, but I have no idea how to add an overlay yet.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mxng** [comment]
@TeeWhyKay 

https://user-images.githubusercontent.com/11084577/134790363-be67cd5f-abec-49cf-aeb7-402f3658c572.mov

**Comment by TeeWhyKay** [comment]
> @TeeWhyKay
> 
>  Screen.Recording.2021-09-26.at.9.42.10.AM-1.mov

that's so cool!! Nice job!

**Review by TeeWhyKay — APPROVED** [review]
Great job on improving the user experience for selecting cuisines

**Pull request merged**
