### PR TITLE
Response input now has default value for lazy people

### PR DESCRIPTION
**Pull request by TeeWhyKay**
## Why

This pull request is needed because:

* Location input field is mandatory but some users might be lazy to fill.
* Rendering new responses has been edited to form partial. Bugs have been occurring when user submits wrong inputs. This has been fixed.

## What

This pull request introduces the following:

 * Location input field is populated with hard coded default value upon loading response page.

### CODE REVIEW

**Review by mxng — APPROVED** [review]
Looks fine

**Review by mxng — CHANGES_REQUESTED** [review]
Problem: It overwrites my input when I edit preferences

**Comment by TeeWhyKay** [comment]
> Problem: It overwrites my input when I edit preferences

Thanks for catching that, updated!

**Review by mxng — APPROVED** [review]
👍 Works great now

**Pull request merged**
