### PR TITLE
Share link button now works on both mobile (chrome) and desktop

### PR DESCRIPTION
**Pull request by TeeWhyKay**
## Why

This pull request is needed because:

* Native sharing on mobile (android chrome)
* Removed ugly link
* A simple share button! :D

[Link to Card](https://trello.com/c/WnBbuvmE)

## What

This pull request introduces the following:

 * On mobile (chrome), native share works

### Screenshot

https://user-images.githubusercontent.com/72695565/135379830-290f909e-08f1-4229-92d7-41a1cc0764f6.mov

### CODE REVIEW

**Comment by TeeWhyKay** [comment]
[share to telegram or whatsapp directly (the sns pop ups on mobile)](https://trello.com/c/WnBbuvmE/194-share-to-telegram-or-whatsapp-directly-the-sns-pop-ups-on-mobile)

**Review by mxng — DISMISSED** [review]
seems fine

**Comment by mxng** [comment]
The share pops up but it gives me "We can't decide where to eat, let's get Chomp to decide for us: " instead of a link

**Comment by TeeWhyKay** [comment]
> The share pops up but it gives me "We can't decide where to eat, let's get Chomp to decide for us: " instead of a link

Feature works only on android chrome browser for now, desktop copy is broken.

**Review by mxng — APPROVED** [review]

**Pull request merged**
