### PR TITLE
Add animate style

### PR DESCRIPTION
**Pull request by mxng**
https://user-images.githubusercontent.com/11084577/134762818-1c0f1982-d5be-4f1f-8c4e-d06b4807e44d.mov

### CODE REVIEW

**Comment by mxng** [comment]
[Make a nice success page (with nice animation) to make them excited about the results](https://trello.com/c/bknwvo52/122-make-a-nice-success-page-with-nice-animation-to-make-them-excited-about-the-results)

**Comment by mxng** [comment]
Is that good enough, or you guys want something like this?

https://tobiasahlin.com/moving-letters/#9

**Comment by tjw0612** [comment]
> Is that good enough, or you guys want something like this?
> 
> https://tobiasahlin.com/moving-letters/#9

Looks good lah, let's start with smth simple first

**Review by tjw0612 — APPROVED** [review]
thanks

**Review by TeeWhyKay — APPROVED** [review]
Bouncy! 🏀

**Review by amelialimyh — APPROVED** [review]
Love it

**Pull request merged**
