### PR TITLE
Update email to show chomp sess link

### PR DESCRIPTION
**Pull request by mxng**
The email now shows the link to edit the chomp session or response
Screenshot 2021-09-25 at 2 08 55 PM

Screenshot 2021-09-25 at 2 09 23 PM

### CODE REVIEW

**Comment by mxng** [comment]
Screenshot 2021-09-25 at 2 22 15 PM


What the email generally looks like now

**Comment by mxng** [comment]
[Email: have the links to the chomp session shown](https://trello.com/c/u33O4jTB/131-email-have-the-links-to-the-chomp-session-shown)

**Review by tjw0612 — APPROVED** [review]
looks good, thanks for making the changes

**Review by TeeWhyKay — APPROVED** [review]
Looks great! Thanks for doing up the responses for the inviter and the participant 🌟

**Review by amelialimyh — APPROVED** [review]
Nice!

**Pull request merged**
