### PR TITLE
move map out of accordian + change timer phrasing

### PR DESCRIPTION
**Pull request by tjw0612**
## Why

This pull request is needed because:

image

image

### CODE REVIEW

**Comment by mxng** [comment]
@tjw0612 Hmm something seems to have changed the way the reviews are displayed:

Before:
Screenshot 2021-09-30 at 10 19 31 AM


After (your branch):

Screenshot 2021-09-30 at 10 19 49 AM

**Comment by mxng** [comment]
Screenshot 2021-09-30 at 10 21 26 AM

Can you make it clearer whether 23 is Hour? Cos some people moight think is 23 mins 59 secs

**Comment by tjw0612** [comment]
> @tjw0612 Hmm something seems to have changed the way the reviews are displayed:
> 
> Before: Screenshot 2021-09-30 at 10 19 31 AM
> 
> After (your branch):
> 
> Screenshot 2021-09-30 at 10 19 49 AM

Accidentally deleted one "/div"

added back and now it looks like this
image

**Comment by tjw0612** [comment]
> Screenshot 2021-09-30 at 10 21 26 AM
> 
> Can you make it clearer whether 23 is Hour? Cos some people moight think is 23 mins 59 secs

Fixed in this pull request
https://github.com/TeeWhyKay/Chomp/pull/123

**Review by mxng — APPROVED** [review]
looks ok, but is this the old timer? since the count down isn't sticky yet

**Pull request merged**
