### PR TITLE
Add favourite icon in restaurant image

### PR DESCRIPTION
**Pull request by amelialimyh**
## Why

This pull request is needed because:

Users cannot save their favourite restaurants

[Link to Card]()

## What

This pull request introduces the following:

 * Allows users to favourite the restaurant that they like

### CODE REVIEW

**Comment by mxng** [comment]
[Add result to bookmarks (favorite)](https://trello.com/c/UtffpuE6/63-add-result-to-bookmarks-favorite)

**Review by mxng — APPROVED** [review]
Looks good!

**Comment by mxng** [comment]
I added some animation so it looks more clickable since is not the standard heart shape.

Is it ok?

https://user-images.githubusercontent.com/11084577/134925533-88441070-0f39-436b-89ab-a160711e4ee7.mov

**Review by tjw0612 — APPROVED** [review]
looks good

**Review by TeeWhyKay — APPROVED** [review]
Looks great! 😍

**Pull request merged**
