### PR TITLE
Seed restaurant website

### PR DESCRIPTION
**Pull request by TeeWhyKay**
## Why

This pull request is needed because:

Restaurants have their actual website for redirection.

## What

This pull request introduces the following:

 * Restaurant model now has their websites from seeding
 * Seeding updated to get the official restaurant website
 * If STB has no official website, link to google search of restaurant name instead.

## Others

New seeding script has been tested and there is no issue.

### CODE REVIEW

**Review by amelialimyh — APPROVED** [review]
Nice

**Review by mxng — CHANGES_REQUESTED** [review]
Could you have the destroy_all functions start at the top of the seed?

The following 3 has to be in order:

Response.destroy_all
ChompSession.destroy_all
Restaurant.destroy_all

in this order, followed by User etc

The seed cannot get through because of dependencies.
I have to manually `rails c` to destroy response first, then chomp session, then restaurant. 
Until then `rails db:seed` or reset would not work for me.

**Comment by TeeWhyKay** [comment]
> Could you have the destroy_all functions start at the top of the seed?
> 
> The following 3 has to be in order:
> 
> Response.destroy_all
> ChompSession.destroy_all
> Restaurant.destroy_all
> 
> in this order, followed by User etc
> 
> The seed cannot get through because of dependencies.
> I have to manually `rails c` to destroy response first, then chomp session, then restaurant.
> Until then `rails db:seed` or reset would not work for me.

Interesting, rails db:reset works fine on my end. I've updated the seed to destroy the data earlier in the seeding process.

**Review by mxng — APPROVED** [review]
Thanks!

**Pull request merged**
